//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA7.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHash", ReplyAction="http://tempuri.org/IService1/GetHashResponse")]
        string GetHash(string pass, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHash", ReplyAction="http://tempuri.org/IService1/GetHashResponse")]
        System.Threading.Tasks.Task<string> GetHashAsync(string pass, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPass", ReplyAction="http://tempuri.org/IService1/GetPassResponse")]
        string GetPass(string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPass", ReplyAction="http://tempuri.org/IService1/GetPassResponse")]
        System.Threading.Tasks.Task<string> GetPassAsync(string hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProjectA7.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProjectA7.ServiceReference1.IService1>, ProjectA7.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHash(string pass, string salt) {
            return base.Channel.GetHash(pass, salt);
        }
        
        public System.Threading.Tasks.Task<string> GetHashAsync(string pass, string salt) {
            return base.Channel.GetHashAsync(pass, salt);
        }
        
        public string GetPass(string hash) {
            return base.Channel.GetPass(hash);
        }
        
        public System.Threading.Tasks.Task<string> GetPassAsync(string hash) {
            return base.Channel.GetPassAsync(hash);
        }
    }
}
